### ISSUE TITLE
Markup not loaded from SGF example file

### ISSUE THREAD

**Issue by yewang** [IlyaKirillov/GoProject#2]
When loading the SGF example file found here:
www.red-bean.com/sgf/examples/
www.red-bean.com/sgf/examples/ff4_ex.sgf

When viewing variation C of the first game tree, in the node testing various markup properties, the markup (TR, CR, SQ, SL, MA) are not shown at all, while only some of the territory marks (TB, TW) are shown. This node should look something like this:
www.red-bean.com/sgf/examples/ex04.gif

**Comment by IlyaKirillov** [comment]
Hello.
Thanks, going to fix it.

2015-03-22 0:47 GMT+03:00 yewang <notifications@github.com>:

**Comment by IlyaKirillov** [comment]
Ok, i got that. Problem - in the same node Common marks  and territory
marks were used, in that case i clean up board from all common marks,
because there is no need in common mark when u r counting scores. And about
territory marks, my application don't use territory marks points from sgf,
cas they are may be wrong, that's why my application offers to count scores
by ur own.

2015-03-22 0:54 GMT+03:00 Ilya Kirillov <kocmohabt.baduk@gmail.com>:
